### ISSUE TITLE
Wrongly shared

### ISSUE THREAD

**Issue by Leela020** [panrafal/depthy#28]
I accidentally shared my cat´s photo to DEPTHY, I thought it was facebook and I would like you to please put it down. I know there is nothing special in the photo but I do not want it to be of public use, so please take it from the page. I am sorry to bother you and thanks for the program.

**Comment by panrafal** [comment]
Don't worry, images on depthy.me are only visible to you, and people you shared them with

**Comment by Leela020** [comment]
Ah ok! Sorry I got worried when it appeared in between the example images. Thank you very much
