### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by Aidoboy** [panrafal/depthy#29]
I have an app that lets me use depth photos as a 3D wallpaper in a way that looks a lot like Depthty. Could there be a link to download photos from Depthy so that I could use them for that?

**Comment by jeviteng** [comment]
Hello!


I am overseas atm, if you have any urgent matters, you may still be able to reach me on Whatsapp/Skype. (WiFi&nbsp;is limited over here!) Otherwise, please correspond with my colleague, Xrystal&nbsp;- (xrystal.toh@silentfrontier.com)


Cheers,

Jevi

**Comment by panrafal** [comment]
You can export them to JPG format from the share menu
