### ISSUE TITLE
depthy.me down! build and run app locally?

### ISSUE THREAD

**Issue by grasshorse757** [panrafal/depthy#47]
hi panrafal, I noticed the depthy.me website has been down for a while. i tried making an Ubuntu virtual machine to install Docker so I could run the app with the instructions in the README.MD, but it says it can't find the app image.

![docker run](https://user-images.githubusercontent.com/66766505/84348837-61a20280-ab8c-11ea-84de-402d200fb8d3.jpg)

anyway, I downloaded this repository and I've been trying a few things to run this app locally but I couldn't do it. I even installed xampp and put the "app" folder inside htdocs, but then it says my browser is outdated (even though I'm using Chrome and it always ran fine).

![localhost depthy chrome](https://user-images.githubusercontent.com/66766505/84348856-72eb0f00-ab8c-11ea-99b8-5a5342b1926e.JPG)

also, in the README.MD there are instructions to build the app:

- Install node + npm
- Run anywhere: npm install -g grunt-cli bower
- Run in project directory: npm install and bower install
- For local development server run: grunt serve
- For deployment: grunt build

but after building, what do we do to be able to run it locally?

thanks in advance!

**Comment by ndahlquist** [comment]
It seems that image no longer exists on Dockerhub. You can use this copy instead:

```
docker run --rm -t -i -p 9000:9000 ndahlquist/depthy
```

(I've also made a PR to update the readme here: https://github.com/panrafal/depthy/pull/48)

**Comment by grasshorse757** [comment]
> It seems that image no longer exists on Dockerhub. You can use this copy instead:
> 
> ```
> docker run --rm -t -i -p 9000:9000 ndahlquist/depthy
> ```
> 
> (I've also made a PR to update the readme here: #48)

thank you! 😄
