### ISSUE TITLE
Depthy.me website hacked

### ISSUE THREAD

**Issue by elammertsma** [panrafal/depthy#50]
Your website at depthy.me is currently redirecting to a lot of spam and malware. Just wanted to let you know so you can hopefully recover it and get it back online. I love using it - especially now with Google's updated camera app and the depth mapping on the Pixel 4.

**Comment by MartinRGB** [comment]
new website address is : http://depthy.stamina.pl/ @elammertsma

**Comment by elammertsma** [comment]
Thanks, that site works!

I've now noticed it doesn't work with newer portrait-mode photos from the Google camera on Pixel phones. I can get it to work by manually extracting the depth map with photopea.com and then loading it separately, but I imagine this should just work out of the box on Depthy. I'll submit a new issue.
